"""Add initial tables

Revision ID: 55b29b2f5224
Revises: 
Create Date: 2024-11-14 14:38:18.282150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b29b2f5224'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customerdetails',
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email_id', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('cust_id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_index(op.f('ix_customerdetails_cust_id'), 'customerdetails', ['cust_id'], unique=False)
    op.create_table('credentials',
    sa.Column('userid', sa.String(length=50), nullable=False),
    sa.Column('pwd_hash', sa.String(length=255), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['customerdetails.cust_id'], ),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_index(op.f('ix_credentials_userid'), 'credentials', ['userid'], unique=False)
    op.create_table('customerbalance',
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('last_transaction_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['customerdetails.cust_id'], ),
    sa.PrimaryKeyConstraint('cust_id')
    )
    op.create_table('transactions',
    sa.Column('transac_id', sa.Integer(), nullable=False),
    sa.Column('dcust', sa.Integer(), nullable=True),
    sa.Column('ccust', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ccust'], ['customerdetails.cust_id'], ),
    sa.ForeignKeyConstraint(['dcust'], ['customerdetails.cust_id'], ),
    sa.PrimaryKeyConstraint('transac_id')
    )
    op.create_index(op.f('ix_transactions_transac_id'), 'transactions', ['transac_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transac_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('customerbalance')
    op.drop_index(op.f('ix_credentials_userid'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_customerdetails_cust_id'), table_name='customerdetails')
    op.drop_table('customerdetails')
    # ### end Alembic commands ###
